### ISSUE TITLE
[TRACKER] collection test failures

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/package-test-results#1]
(All the collections that have been retired from Ansible 10.3.0 or otherwise no longer have sanity test failures in that version should be checked off.)

``` bash
./main.py -i data/9/ansible-9.1.0-sanity.yaml -t build/ansible-build-data/9/ansible-9.1.0-tags.yaml -u data/9/ansible-9.1.0-missing-upstreams.yaml failures --bullet="- [ ]" --reverse | wl-copy
```
- [ ] cisco.intersight -- https://github.com/CiscoDevNet/intersight-ansible/issues/108
    15512 validate-modules
- [ ] fortinet.fortimanager -- https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/issues/80, https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/issues/93
    13015 validate-modules
- [ ] cisco.ucs -- https://github.com/CiscoDevNet/ansible-ucs/issues/40
    9502 validate-modules
- [x] ovirt.ovirt (upstream runs the tests but has their own script to preprocess their sources which we cannot run here)
    136 WRONG_HASH
    113 yamllint
    66 validate-modules
    60 compile-python-3.10
    60 compile-python-3.11
    60 compile-python-3.12
    59 compile-python-2.7
    59 compile-python-3.6
    59 compile-python-3.7
    59 compile-python-3.8
    59 compile-python-3.9
    11 ansible-doc
    1 WRONG_GALAXY_YML_NAME
- [x] community.network -- https://github.com/ansible-collections/community.network/issues/591 (exclusion discussion started in https://forum.ansible.com/t/should-we-remove-community-network-from-the-ansible-community-package/8030)
    654 BANNED_SANITY
- [ ] check_point.mgmt -- https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/issues/121, https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/issues/142
    240 validate-modules
    120 WRONG_HASH
    3 ansible-doc
- [x] netapp_eseries.santricity -- https://github.com/NetApp/santricity/issues/23
    342 validate-modules
    3 ansible-doc
    2 yamllint
- [x] azure.azcollection -- https://github.com/ansible-collections/azure/issues/1417
    311 validate-modules
- [x] google.cloud -- https://github.com/ansible-collections/google.cloud/issues/613
    186 validate-modules
- [x] theforeman.foreman -- https://github.com/theforeman/foreman-ansible-modules/issues/1703 (upstream runs the tests but has their own script to preprocess their sources which we cannot run here)
    153 yamllint
- [ ] wti.remote -- https://github.com/wtinetworkgear/wti-collection/issues/15, https://github.com/wtinetworkgear/wti-collection/issues/17
    85 validate-modules
    7 ansible-doc
    4 yamllint
- [x] hpe.nimble -- https://github.com/hpe-storage/nimble-ansible-modules/issues/63
    25 validate-modules
    23 compile-python-2.7
- [x] infinidat.infinibox -- https://github.com/Infinidat/ansible-infinidat-collection/issues/19
    24 validate-modules
    3 compile-python-3.10
    3 compile-python-3.11
    3 compile-python-3.12
    1 compile-python-2.7
- [ ] kubernetes.core -- https://github.com/ansible-collections/kubernetes.core/issues/672
    25 validate-modules
    9 yamllint
- [x] cisco.ise -- https://github.com/CiscoISE/ansible-ise/issues/117
    15 validate-modules
    7 ansible-doc
    1 yamllint
- [ ] dellemc.unity -- https://github.com/dell/ansible-unity/issues/47
    18 validate-modules
    3 compile-python-2.7
- [x] netapp.azure -- https://github.com/ansible-collections/netapp.azure/issues/9 (removed)
    16 validate-modules
- [x] gluster.gluster -- https://github.com/gluster/gluster-ansible-collection/issues/31
    10 validate-modules
- [ ] community.sap_libs -- https://github.com/sap-linuxlab/community.sap_libs/issues/38
    9 validate-modules
- [ ] sensu.sensu_go -- https://github.com/sensu/sensu-go-ansible/issues/362
    7 validate-modules
    1 WRONG_HASH
- [x] community.okd -- https://github.com/openshift/community.okd/issues/219
    7 validate-modules
- [ ] openstack.cloud -- https://bugs.launchpad.net/ansible-collections-openstack/+bug/2050854
    5 compile-python-2.7
    2 yamllint
- [x] community.digitalocean -- https://github.com/ansible-collections/community.digitalocean/issues/347
    4 validate-modules
    2 compile-python-2.7
- [x] purestorage.fusion -- https://github.com/Pure-Storage-Ansible/Fusion-Collection/issues/166
    6 compile-python-2.7
- [x] netapp.um_info -- https://github.com/ansible-collections/netapp.um_info/issues/11 (removed)
    5 validate-modules
- [x] community.general -- https://github.com/ansible-collections/community.general/issues/7884
    4 BANNED_SANITY
- [x] community.mysql -- https://github.com/ansible-collections/community.mysql/issues/608
    4 BANNED_SANITY
- [x] netapp.aws -- https://github.com/ansible-collections/netapp.aws/issues/9 (removed)
    4 validate-modules
- [x] ansible.posix -- https://github.com/ansible-collections/ansible.posix/issues/528
    3 BANNED_SANITY
- [x] chocolatey.chocolatey -- https://github.com/chocolatey/chocolatey-ansible/issues/144
    3 validate-modules
- [ ] cyberark.conjur -- https://github.com/cyberark/ansible-conjur-collection/issues/201
    2 yamllint
    1 validate-modules
- [x] ibm.spectrum_virtualize (DEPRECATED)
    3 WRONG_HASH
- [ ] awx.awx
    1 BANNED_SANITY
    1 WRONG_HASH
- [ ] cisco.mso -- https://github.com/CiscoDevNet/ansible-mso/issues/572
    2 validate-modules
- [ ] community.mongodb
    2 yamllint
- [x] community.sap -- https://github.com/ansible-collections/community.sap/issues/32
    2 yamllint
- [x] lowlydba.sqlserver
    2 WRONG_HASH
- [ ] netbox.netbox
    2 compile-python-2.7
- [x] vmware.vmware_rest
    2 validate-modules
- [x] cisco.asa
    1 compile-python-2.7
- [ ] cisco.dnac -- https://github.com/cisco-en-programmability/dnacenter-ansible/issues/208
    1 compile-python-2.7
- [x] community.postgresql -- Fixed https://github.com/ansible-collections/community.postgresql/pull/664
    1 BANNED_SANITY
- [x] community.zabbix
    1 compile-python-2.7
- [x] containers.podman
    1 compile-python-2.7
- [x] netapp.storagegrid
    1 validate-modules
- [x] purestorage.flasharray
    1 compile-python-2.7
- [ ] cyberark.pas -- https://github.com/cyberark/ansible-security-automation-collection/issues/74
    2 WRONG_HASH
    1 validate-modules
- [ ] netapp.ontap — https://github.com/ansible-collections/netapp.ontap/issues/224
- [ ] cisco.aci -- https://github.com/CiscoDevNet/ansible-aci/issues/710

**Comment by mariolenz** [comment]
I think you shoud ignore hpe.nimble and gluster.gluster:

* ansible-community/ansible-build-data#285
* ansible-community/ansible-build-data#249

**Comment by mariolenz** [comment]
BTW I see purestorage.fusion on your list. It looks like this collection [will be deprecated](https://forum.ansible.com/t/3712). So maybe you can ignore this, too.

**Comment by mariolenz** [comment]
> BTW I see purestorage.fusion on your list. It looks like this collection [will be deprecated](https://forum.ansible.com/t/3712). So maybe you can ignore this, too.

@gotmax23 This collection has been deprecated by it's maintainers and we will ansible-community/ansible-build-data#374

**Comment by gotmax23** [comment]
Results for 10.3.0 are listed below and also represented in https://github.com/ansible-community/package-test-results/tree/main/rendered/10.3.0

- [ ] cisco.intersight
    15582 validate-modules
- [ ] cisco.ucs
    9502 validate-modules
- [ ] ovirt.ovirt
    136 WRONG_HASH
    113 yamllint
    66 validate-modules
    60 compile-python-3.10
    60 compile-python-3.11
    60 compile-python-3.12
    59 compile-python-3.7
    59 compile-python-3.8
    59 compile-python-3.9
    11 ansible-doc
    1 WRONG_GALAXY_YML_NAME
- [ ] community.network
    654 BANNED_SANITY
- [ ] netapp_eseries.santricity
    342 validate-modules
    3 ansible-doc
    2 yamllint
- [ ] check_point.mgmt
    261 validate-modules
    4 WRONG_HASH
- [ ] google.cloud
    186 validate-modules
- [ ] theforeman.foreman
    122 yamllint
- [ ] wti.remote
    85 validate-modules
    7 ansible-doc
    4 yamllint
- [ ] ansible.posix
    9 validate-modules
- [ ] sensu.sensu_go
    7 validate-modules
    1 WRONG_HASH
- [ ] netapp.ontap
    4 validate-modules
- [ ] chocolatey.chocolatey
    3 validate-modules
- [ ] cyberark.conjur
    2 yamllint
    1 validate-modules
- [ ] cyberark.pas
    2 WRONG_HASH
    1 validate-modules
- [ ] ibm.spectrum_virtualize
    3 WRONG_HASH
- [ ] kubernetes.core
    3 BANNED_SANITY
- [ ] awx.awx
    1 BANNED_SANITY
    1 WRONG_HASH
- [ ] community.mongodb
    2 yamllint
- [ ] community.okd
    2 BANNED_SANITY
- [ ] ibm.storage_virtualize
    2 WRONG_HASH
- [ ] inspur.ispim
    2 WRONG_HASH
- [ ] kubevirt.core
    2 WRONG_HASH
- [ ] openstack.cloud
    2 yamllint

**Comment by gotmax23** [comment]
Followed up with:

- [ ] https://github.com/wtinetworkgear/wti-collection/issues/15

(Will follow up again in a couple weeks)

**Comment by gotmax23** [comment]
@gundalow followed up with

- [ ] https://github.com/NetApp/santricity/issues/23

(We should follow up again in a couple weeks)

**Comment by gotmax23** [comment]
- [ ] https://github.com/CiscoDevNet/ansible-ucs/issues/40 (current results at https://github.com/ansible-community/package-test-results/blob/main/rendered/10.3.0/cisco.ucs.md)
- [ ] https://github.com/CiscoDevNet/intersight-ansible/issues/108 (current results at https://github.com/ansible-community/package-test-results/blob/main/rendered/10.3.0/cisco.intersight.md)

are also a problem. The maintainer says that our results are broken and differ from the results reported by Automation Hub. Perhaps there are sanity ignore entries that are not included in the git repository. Otherwise, I am at a loss.

**Comment by gotmax23** [comment]
@gundalow, any idea what's going on with the Cisco collections? Looking at the output in https://console.redhat.com/ansible/automation-hub/repo/published/cisco/intersight/import-log/, it seems that AH doesn't run the validate-modules test which is one that we require to pass.

**Comment by gotmax23** [comment]
A discussion about community.network has been started in https://forum.ansible.com/t/should-we-remove-community-network-from-the-ansible-community-package/8030.

**Comment by felixfontein** [comment]
> * [ ]  [Community package requirements: sanity tests CiscoDevNet/ansible-ucs#40](https://github.com/CiscoDevNet/ansible-ucs/issues/40) (current results at https://github.com/ansible-community/package-test-results/blob/main/rendered/10.3.0/cisco.ucs.md)
> 
>     * [ ]  [Community package requirements: sanity tests CiscoDevNet/intersight-ansible#108](https://github.com/CiscoDevNet/intersight-ansible/issues/108) (current results at https://github.com/ansible-community/package-test-results/blob/main/rendered/10.3.0/cisco.intersight.md)
> 
> 
> are also a problem. The maintainer says that our results are broken and differ from the results reported by Automation Hub. Perhaps there are sanity ignore entries that are not included in the git repository. Otherwise, I am at a loss.

It turned out that this is actually due to a bug in ansible-test (https://github.com/ansible/ansible/issues/83842). On the other hand, if Automation Hub's sanity tests accepted it, it means that AH doesn't run the validate-modules sanity test. This basically means that successful import in AH doesn't mean that all sanity tests pass. (But it also doesn't mean that the ones not run fail...)

**Comment by gotmax23** [comment]
10.4.0


- [x] ovirt.ovirt
    136 WRONG_HASH
    113 yamllint
    66 validate-modules
    60 compile-python-3.10
    60 compile-python-3.11
    60 compile-python-3.12
    59 compile-python-3.7
    59 compile-python-3.8
    59 compile-python-3.9
    11 ansible-doc
    1 WRONG_GALAXY_YML_NAME
- [x] community.network
    654 BANNED_SANITY
- [ ] netapp_eseries.santricity
    342 validate-modules
    3 ansible-doc
    2 yamllint
- [x] check_point.mgmt
    261 validate-modules
    4 WRONG_HASH
- [ ] google.cloud
    203 validate-modules
- [x] theforeman.foreman
    122 yamllint
- [x] wti.remote
    85 validate-modules
    4 WRONG_HASH
- [ ] ansible.posix
    9 validate-modules
- [ ] sensu.sensu_go
    7 validate-modules
    1 WRONG_HASH
- [ ] dellemc.openmanage
    4 WRONG_HASH
- [ ] netapp.ontap
    4 validate-modules
- [ ] chocolatey.chocolatey
    3 validate-modules
- [ ] cyberark.conjur
    2 yamllint
    1 validate-modules
- [ ] cyberark.pas
    2 WRONG_HASH
    1 validate-modules
- [ ] ibm.spectrum_virtualize
    3 WRONG_HASH
- [ ] kubernetes.core
    3 BANNED_SANITY
- [ ] awx.awx
    1 BANNED_SANITY
    1 WRONG_HASH
- [ ] community.mongodb
    2 yamllint
- [ ] community.okd
    2 BANNED_SANITY
- [ ] ibm.storage_virtualize
    2 WRONG_HASH
- [ ] inspur.ispim
    2 WRONG_HASH
- [ ] kubevirt.core
    2 WRONG_HASH
- [ ] openstack.cloud
    2 yamllint
- [ ] cisco.intersight
    1 WRONG_HASH
- [ ] dellemc.enterprise_sonic
    1 WRONG_HASH
Total: 25

**Comment by mariolenz** [comment]
@gotmax23 You've started and named this issue `[TRACKER] 9.1.0 collection test failures`. But in your last comment you mention 10.4.0. I'm a little bit confused...

I suggest to open an new `[TRACKER] 10.x collection test failures` (and a `[TRACKER] 11.x collection test failures` once it's been released) issue. And close this one once Ansible 9.x is EOL. I think this would make it easier for us to keep track.

What do you think?

**Comment by gotmax23** [comment]
I removed the version number from the issue name. The idea is — for now — to use this issue on a rolling basis to track changes for whatever the latest release is.

**Comment by gotmax23** [comment]
(Duplicates that are already listed in the issue description and that have had issues filled already should be checked off here.)

11.0.0

- [ ] fortinet.fortimanager
    14261 validate-modules
- [ ] ovirt.ovirt
    136 WRONG_HASH
    113 yamllint
    66 validate-modules
    60 compile-python-3.11
    60 compile-python-3.12
    60 compile-python-3.13
    59 compile-python-3.10
    59 compile-python-3.8
    59 compile-python-3.9
    11 ansible-doc
    1 WRONG_GALAXY_YML_NAME
- [ ] community.network
    654 BANNED_SANITY
    1 validate-modules
- [ ] netapp_eseries.santricity
    342 validate-modules
    3 ansible-doc
    2 yamllint
- [ ] google.cloud
    203 validate-modules
- [ ] theforeman.foreman
    122 yamllint
- [ ] dellemc.unity
    18 validate-modules
- [ ] awx.awx
    14 validate-modules
    1 WRONG_HASH
- [ ] community.sap_libs
    9 validate-modules
- [ ] sensu.sensu_go
    7 validate-modules
    1 WRONG_HASH
- [ ] wti.remote
    8 WRONG_HASH
- [ ] community.okd
    6 validate-modules
- [ ] cisco.dnac
    5 validate-modules
- [ ] cisco.mso
    5 validate-modules
- [ ] netapp.ontap
    4 validate-modules
- [ ] chocolatey.chocolatey
    3 validate-modules
- [ ] cisco.aci
    3 validate-modules
- [ ] cyberark.conjur
    2 yamllint
    1 validate-modules
- [ ] cyberark.pas
    2 WRONG_HASH
    1 validate-modules
- [ ] ibm.spectrum_virtualize
    3 WRONG_HASH
- [ ] kubernetes.core
    3 BANNED_SANITY
- [ ] arista.eos
    2 validate-modules
- [ ] check_point.mgmt
    2 WRONG_HASH
- [ ] community.mongodb
    2 yamllint
- [ ] inspur.ispim
    2 WRONG_HASH
- [ ] kubevirt.core
    2 WRONG_HASH
- [ ] openstack.cloud
    2 yamllint
- [ ] cisco.meraki
    1 BANNED_SANITY

Total: 28

**Comment by mariolenz** [comment]
community.network, google.cloud and sensu.sensu_go will be removed from Ansible 12: ansible-community/ansible-build-data#504

Should we mention this in your list somehow? Maybe something like:

>     * [x] community.network (ansible-community/ansible-build-data#475)
>       654 BANNED_SANITY
> 
>     * [x] google.cloud (ansible-community/ansible-build-data#476)
>       203 validate-modules
> 
>     * [x] sensu.sensu_go (ansible-community/ansible-build-data#463)
>       7 validate-modules
>       1 WRONG_HASH

**Comment by gotmax23** [comment]
My goal for this issue is more to keep track of *whether or not* the issues have been resolved as opposed to *how* (either it's been fixed or the collection has been scheduled for removal), but if you feel that information is helpful, feel free to add it. At some point, I'll also update the script to not list collections that are already scheduled for removal, as we now have structured data about removed collections in the collection-meta file.

**Comment by mariolenz** [comment]
Since you don't object, I've added the information about collection removal. At the end of the day, I think this information is helpful. If we will remove a collection because it's officially / we consider it unmaintained, we know that we don't have to have a closer look at it.

BTW Do you think that duplicates that are already listed in the issue description and that have had issues filled already should be checked off? For example, are the ovirt.ovirt issues in Ansible 9 really the same ones as in Ansible 11?

**Comment by gotmax23** [comment]
> BTW Do you think that duplicates that are already listed in the issue description and that have had issues filled already should be checked off? For example, are the ovirt.ovirt issues in Ansible 9 really the same ones as in Ansible 11?

The issue with ovirt.ovirt is that upstream runs the tests in CI but has their own script to preprocess their sources which this repo's tooling does not use. I've just been ignoring it for now. In general, I'm using the issue description to keep track of all open issues. Some collections in the description have multiple issues listed under them, because the original issues were closed, and then I opened new issues after new failures were found in later versions of the collection.
